---
contentdir: "content"
layoutdir: "layouts"
publishdir: "public"
indexes:
  category: "categories"
baseurl: "http://rayliao.github.io/nowhere"
title: "nowhere"
canonifyurls: true
theme: "herring-cove"
...